index.js, package.json, src/render.js, src/tag.js, tags/assign.js, tags/capture.js, tags/cycle.js, tags/for.js, tags/include.js, tags/layout.js, tags/raw.js, tags/tablerow.js, test/error.js, test/filters.js, test/liquid.js, test/render.js, test/tags.js
All tests are passing except the express tests in tests/liquid.js.  I commented those out for now.
=> Conversion to Async

index.js
=> Add strict* options to Express engine shortcut

tags/for.js
eg:
```twig
{% for i in (1..15) reversed limit:4 offset:2 %}
{{ i }}
{% endfor %}
{% for i in (1..15) limit:4 reversed offset:2 %}
{{ i }}
{% endfor %}
{% for i in (1..15) limit:4 offset:2 reversed %}
{{ i }}
{% endfor %}
```
=> reversed position

src/scope.js, test/filters.js
Size can also be used with dot notation (for example, {{ my_string.size }})
=> Size can also be used with dot notation

src/tokenizer.js
Adds indentation to token.
This information could be useful for custom tags.
=> add identation value to token

src/tokenizer.js
With this PR it now matches the intended functionality; i.e., https://github.com/harttle/liquidjs/wiki/Whitespace-Control
=> Support `{{-` and `-}}` for whitespace control.

tags/for.js, test/tags/for.js
Ref: https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#allowed-collection-types
=> Fixes #42: make `for` tag iterate objects like Shopify liquid.

src/filter.js, test/filter.js, test/filters.js
fixes #63 
includes tests.  all tests pass except the 6 (already failing) strftime tests
=> fix dupe name bug

src/lexical.js, test/syntax.js
=> fix: correctly understand variables with question marks

README.md, src/render.js, src/scope.js, src/util/underscore.js, test/render.js, test/scope.js, test/util/underscore.js
Fix:
* circular structure exception when calling JSON.stringify
* String type checking before stringify
Feature:
* `to_liquid()` and its `toLiquid()` alias
=> output stringify

README.md
the example didn't work. this fixed it for me
=> Fix Register Tags example

src/builtin/filters/string.ts, test/integration/builtin/filters/string.ts
This addresses #142 
Please let me know if this should be addressed in a different way. Thanks!
=> Fix: Stringify append and prepend values

src/template/value.ts, test/unit/parser/tokenizer.ts, test/unit/template/value.ts
=> Fix quotation tokenizing

src/builtin/tags/case.ts
The case condition was evaluated for every branch
=> perf: prevent multiple case evaluations

src/util/error.ts
closes https://github.com/harttle/liquidjs/issues/337
=> feat: add context as a property on the LiquidError

docs/source/tutorials/contribution-guidelines.md
=> Typo fixed

docs/source/filters/uniq.md
=> docs: fix uniq filter example in the docs

docs/source/filters/remove_first.md
=> docs: fix remove_first example output

src/drop/comparable.ts, test/integration/drop/drop.spec.ts
This pull request enhances the `isComparable` function to ensure it fully implements the `Comparable` interface, which includes the methods `equals`, `gt`, `geq`, `lt`, and `leq`.
The `isComparable` function has been improved to check for the complete implementation of the `Comparable` interface. This ensures that the function correctly identifies objects that are meant to be compared using the methods of the `Comparable` interface.
- **Modified File**: `src/drop/comparable.ts`
- **Function Modified**: `isComparable`
Fixes #700
---
=> fix: isComparable full interface check

package.json
ran into some tree shaking issues
=> fix: add sideEffects=false to package.json

docs/source/tutorials/register-filters-tags.md
Noticed these variables were incorrect in the docs
=> docs: Update register-filters-tags.md to reference correct variables

docs/source/tutorials/options.md
Replaced square brackets with round ones in a link markup.
=> docs: A lil Markdown fix

docs/source/tutorials/options.md
=> docs: Fix typo in options.md
