src/filter.js
src/lexical.js
test/filters.js
test/lexical.js

Custom Filter
```js
liquid.registerFilter('obj_test', (...v) => v.join(','));
```
Liquid
```twig
{{ "a" | obj_test: k1: "v1", k2: "v2" }}
```
Output
```
a,k1,v1,k2,v2
```
A fly in the ointment is the filter returns the arguments are array, need array2object processing:
array [key,value] to object {key: value} 
```js
liquid.registerFilter('obj_test', (v, ...args) => {
var obj = {};
for (var i = 0; i < args.length; i++) {
var arg = args[i];
if (i % 2 == 0) {
obj[arg] = 1 + i;
}
}
for (var arg in obj) {
obj[arg] = args[obj[arg]] || '';
}
// v, obj
// console.log(v, obj);
// ...
return;
});
```

Support create variables on the filter line.

---

src/syntax.js
tags/for.js
test/tags/for.js
test/tags/if.js
test/tags/unless.js

For details, see https://shopify.github.io/liquid/basics/truthy-and-falsy/

All values in Liquid are truthy except nil and false.

---

src/lexical.js
src/tokenizer.js
test/tag.js
test/tokenizer.js

It would be great that shopify-liquid could handle multiline tags for example
{% tag d1:'a'
d2:'b'
d3:'c'
%}
This is useful if we have very long lines of parameters/attributes passed to tag
In JS there isn't "dotall" modifier but this can be solved using [\s\S] modifier to replace ".".
See more http://stackoverflow.com/questions/1068280/javascript-regex-multiline-flag-doesnt-work

support multiline tags

---

tags/for.js

The `stop` and `skip` properties of `forloop` are unused since this commit: 951225fb75141a235b4d2e52de4b8dda585a1ccd

Remove unused `stop` and `skip` from `forloop` object

---

src/util/underscore.js
tags/for.js

This allows `for...in` loops to work with `{}` or `Object.create(null)`.
I added `isObject` and `isEmpty` for cleaner `if` statements. I can remove those if you prefer.

Iterate keys of object when used with `for...in` loop

---

src/scope.js

Corrects a bug where `foo.bar[0].foo` results in error: 'Cannot read property `foo` of undefined', because the sequence contains an empty string; i.e., `seq.push('')` should be avoided.
Another possible solution would be to strip empty strings from the final `seq` variable, but this PR fixes the immediate problem.

Bug fix for `foo.bar[0].foo` that is not working.

---

package.json

Depending on this package causes an error in Webpack and other similar browser-side module bundlers as the Node.js core modules are not available. This change simply tells the bundler to ignore the fs package in browser environments.

Ignore "fs" module in browser environments

---

benchmark/index.ts
benchmark/layout.ts
benchmark/templates/layout.liquid
src/liquid.ts

Checking for file existence is unnecessary (and consumes IO) when cache already contains entry.
Contributed a little benchmark suite that measures the improvement:
Before:
```
--- layout ---
cache=false x 2,013 ops/sec ±12.06% (55 runs sampled)
cache=true x 4,865 ops/sec ±8.44% (67 runs sampled)
```
After:
```
--- layout ---
cache=false x 2,149 ops/sec ±11.38% (57 runs sampled)
cache=true x 7,716 ops/sec ±2.93% (70 runs sampled)
```

perf: improve getTemplate() when cache is enabled

---

README.md
src/liquid-options.ts
src/liquid.ts
test/integration/liquid/fs-option.ts

As discussed in #131 , this PR exposes a new `fs` option that allows to change how files are read from the file-system. The `fs` module is used while rendering "partials" and "includes" and also when calling `engine.renderFile()`.
The option is optional. When omitted, the engine follows the current behavior of loading via the native `fs` module (Node.js) or via an AJAX request (browser).
Overriding the `fs` option can be used for specific use cases. Examples:
- Reading partials/includes from memory (see #20).
- Preventing access to some files or directories, or blocking access to the file system altogether (see #131).
Closes #131 
Feedback appreciated 🙇

Expose `fs` as an option to override the default implementations

---

src/builtin/filters/html.ts
test/integration/builtin/filters/html.ts

The built-in escape filters renders "undefined" when the input is undefined :
````javascript
// myObj does not exist
const ret = await engine.parseAndRender(`{{ myObj.someProp | escape }}`)
expect(ret).toBe("") //  Expected: "" but Received: "undefined"
````
This PR fixes it.

fix: escape filter when input is undefined

---

benchmark/index.ts
benchmark/memory.ts
benchmark/templates/lorem-html.liquid
rollup.config.ts
src/parser/flatten/browser.ts
src/parser/flatten/node.ts
src/parser/tokenizer.ts

Fixes #161 
As discussed in #161, this PR applies a performance optimization to reduce the memory footprint of parsed templates that are held in memory. The implementation tries to "flatten" the string's memory representation.
After a few trials, the only implementation that works in Node 8.x, 10.x and 12.x is to convert the string to a `Buffer` instance and back to a string.
This PR also adds a memory footprint benchmark suite.
Here are the results of running the benchmarks before/after the change:
**Before change**
```
--- output ---
literal x 12,549 ops/sec ±5.10% (66 runs sampled)
truncate x 16,438 ops/sec ±6.61% (66 runs sampled)
date x 16,108 ops/sec ±4.62% (69 runs sampled)
escape x 21,418 ops/sec ±4.92% (72 runs sampled)
default x 17,142 ops/sec ±6.03% (71 runs sampled)
--- tag …
```

perf: add string flattening to reduce retained memory (node only)

---

bin/liquid.js

If you pass a JSON file or JSON string as the first argument to the CLI, you can use variables in your templates that get parsed by the CLI.

Add ability to pass JSON context to CLI

---

src/liquid.ts

The call to `fs.readFileSync` in `parseFile` was missing `this`, resulting in a "Not Found" runtime error when trying to use a custom fs implementation with `readFileSync`.  Things worked correctly after I added `this`.
I noticed `fallback` had the same problem so I added it there as well.  I didn't find any other instances.

fix: add `this` to fs references in parseFile

---

package.json

Fixed PR via https://github.com/harttle/liquidjs/pull/189#issuecomment-586281885

fix: add funding entry to show up in npm fund command

---

src/builtin/tags/include.ts
test/integration/builtin/tags/include.ts

Adds a `getText()` missing in #205. Without it the error message started always with `illegal filename "[object Object]"`

fix: return variable name in include error

---

src/liquid-options.ts
src/liquid.ts
test/integration/liquid/cache.ts

I tried to disable the cache for a single renderFile call and discovered this bug. 
The passed in cache option would always be ignored.

fix: respect cache render options

---

docs/source/tags/for.md

This extremely helpful information was found at https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#allowed-collection-types
Also tweaked line 11, which seemed a confusing fragment of the [Shopify documentation](https://shopify.dev/docs/themes/liquid/reference/tags/iteration-tags#for).

docs: Add hashes to `for` tag documentation

---

package.json
rollup.config.ts
test/e2e/xhr.ts

In this diff I fixed es modules distribution for bundlers.
Before we had two problems
- bundlers use "module" field to find es module build
- bundlers cannot use provided es module with node target
In this diff I addressed both of them. Now "main" and "module" fields
points to "node" specific versions. "browser" field provides aliases
with browser compatible builds.
All modern browsers support both "module" and "browser" fields.

feat: setup universal browser and node builds

---

docs/source/tutorials/options.md
src/builtin/filters/array.ts
src/builtin/filters/object.ts
src/builtin/tags/if.ts
src/builtin/tags/unless.ts
src/liquid-options.ts
src/render/boolean.ts
src/render/expression.ts
src/render/operator.ts
test/unit/render/boolean.ts

This is related to ticket https://github.com/harttle/liquidjs/issues/255
I was not able to make a Chinese translation of the document.  Also there are 3 unrelated tests failing that were failing before my changes. Here they are:
```
3 failing
1) util/strftime
Date (Year, Month, Day)
should format %q as date suffix:
AssertionError: expected 'th' to equal 'st'
+ expected - actual
-th
+st
at Context.<anonymous> (test/unit/util/strftime.ts:40:30)
2) util/strftime
Date (Year, Month, Day)
%j
should take count of leap years:
AssertionError: expected '059' to equal '060'
+ expected - actual
-059
+060
at Context.<anonymous> (test/unit/util/strftime.ts:29:34)
3) util/strftime
Date (Year, Month, Day)
%j
should take count of leap years:
AssertionError: expected '060' to equal '061'
+ expected - …
```

Added jsTruthy flag to constuctor in order to enable JS style truthiness evaluation

---

src/parser/tokenizer.ts
src/render/expression.ts
src/tokens/property-access-token.ts
test/e2e/issues.ts
test/unit/parser/tokenizer.ts
test/unit/tokens/property-access-token.ts

Parses braced property accesses similar to how Ruby Liquid does it. Fixes #259

Add explicit braced property access parsing

---

docs/source/tutorials/options.md
src/builtin/tags/if.ts
src/builtin/tags/unless.ts
src/context/context.ts
src/liquid-options.ts
src/render/expression.ts
src/template/value.ts
src/util/error.ts
test/integration/liquid/liquid.ts
test/integration/liquid/strict.ts

Resolve #265 
Implemented solution 1 as discussed in the issue. The option is called `lenientIf` (default off).
It's a bit messy because we want to modify behavior only in very specific situations. This is the cleanest I could come up with; hope it's fine.

lenientIf option: Make 'if' and 'default' more useful with undefined variables

---

src/builtin/filters/date.ts
src/liquid-options.ts
src/util/strftime.ts
test/integration/builtin/filters/date.ts
test/stub/render.ts

Adds timezone offset parsing (e.g. `1990-12-31T23:00:00+02:00`) and mangling the pre-format date object to the right timestamp.
I'm not sure if it even makes sense for this to go in as is, because to me the default behavior of formatting timezoned dates to the local timezone automatically makes sense most of the time in web context: e.g. blogs might usually want to show dates in user-local format. However, configuring timezone preservation in the liquid filter is also a bit weird, since for instance in node.js we will probably always want to preserve the timezone.
What about configuring this in liquid-options?
(eventually) fixes #236

feat: parse and handle date timezone offsets

---

src/tokens/operator-token.ts
test/integration/liquid/operators-option.ts

This fixes a small bug with custom operators introduced in #301; the `precedence` object helped to define when an operator was passed the literal value vs. a boolean. `0` is meant for `and/or`, and `1` for every other comparator - but custom operators would receive a value of `undefined`, which evaluated to falsy. This meant that custom operators wouldn't get the expected arguments:
```
{% if "foo" isFooBar "bar" or "foo" == "bar" %}True{% else %}False{% endif %}
```
`isFooBar` would receive:
```js
function isFooBar (l, r) {
console.log(l, r)
// => "foo", false
}
```
This PR falls back to a precedence of `1` for any token that isn't explicitly hard-coded (the default operators). Technically, this limits the functionality of custom operators but I think that's a reasonable tradeoff; I …

fix: default to precedence 1 for custom operators

---

src/liquid.ts
src/util/error.ts

This exports the errors, so `instanceof LiquidError` checks can be done in user-land.

feat: export errors for better error handling in user-land

---

src/util/error.ts

Follow-up for https://github.com/harttle/liquidjs/pull/338 as I accidentally declared the context property as private...

fix: make LiquidError context property public

---

src/builtin/tags/for.ts
src/builtin/tags/render.ts
src/builtin/tags/tablerow.ts
src/drop/forloop-drop.ts
src/drop/tablerowloop-drop.ts
test/integration/builtin/tags/for.ts

Adds support for forloop.name as found in the [Ruby Shopify liquid implementation](https://www.rubydoc.info/github/Shopify/liquid/Liquid/For#collection_name-instance_method).
```liquid
{% for i in (1..5) limit: 1 %} {{ forloop.name }} {% endfor %}
```
```liquid
{% for item in collection limit: 1 %} {{ forloop.name }} {% endfor %}
```
```liquid
{% for field in obj.fields limit: 1 %} {{ forloop.name }} {% endfor %}
```
```liquid
{% for string in "string" limit: 1 %} {{ forloop.name }} {% endfor %}
```
I can't think of a situation where this would not be backwards compatible, unless someone was relying on the exact output of dumping `{{ forloop }}` not including extra field(s).
This feature can be useful in templating and plugins, to get more context about the loop you're rendering within.

feat: implement `forloop.name` as found in ruby shopify/liquid

---

src/builtin/tags/echo.ts
src/builtin/tags/index.ts
src/builtin/tags/liquid.ts
src/parser/tokenizer.ts
src/tokens/liquid-tag-token.ts
test/e2e/issues.ts
test/integration/builtin/tags/echo.ts
test/integration/builtin/tags/liquid.ts
test/unit/parser/tokenizer.ts

Adds support for `liquid` and `echo` tags. As found in [Ruby Liquid](https://shopify.github.io/liquid/tags/template/) since version 5.0.0.
`echo` is a tag equivalent of the output statement (`{{ ... }}`) and is intended to be used inside `liquid` tags, where output statements are not allowed.
**Input**
```liquid
{% assign username = 'Bob' %}
{% echo username | append: ", welcome to LiquidJS!" | capitalize %}
```
**Output**
```text
Bob, welcome to LiquidJS!
```
`liquid` allows you to combine multiple Liquid tags in a concise, shorthand syntax. Omitting the usual tag start and end sequences (`{%` and `%}`), each line starts with a tag name and, separated by spaces or tabs, finishes with the tag's expression.
**Input**
```liquid
{% liquid
assign names = 'Bob, Sally' | split: ', '
for name in …
```

feat: implement `liquid` and `echo` tags, see #428

---

src/parser/tokenizer.ts

The matchOperator function has a default value of str.length for the end parameter

fix: remove limit on operator char length

---

src/builtin/filters/array.ts
test/integration/builtin/filters/array.ts

The where-filter didn't handle nulls/undefineds properly. The comparison of NullDrop and null would fail and the list would be empty.

fix: where-filter null handling improved

---

docs/themes/navy/layout/index.swig

Swig is rendering the `{{v}}` to nothing in the template, making the example in the docs very confusing. <img width="757" alt="Screenshot 2022-02-16 at 10 14 04" src="https://user-images.githubusercontent.com/1557563/154232792-bea23ca7-ebcb-4626-8b09-0ee9c2446e40.png">

docs: fix example in main docs page

---

docs/source/_data/sidebar.yml
docs/source/tags/inline_comment.md
src/builtin/tags/index.ts
src/builtin/tags/inline-comment.ts
src/parser/tokenizer.ts
src/tokens/liquid-tag-token.ts
src/tokens/tag-token.ts
test/integration/builtin/tags/inline-comment.ts
test/unit/parser/tokenizer.ts

This pull request implements the inline comment tag, as found in [Ruby Liquid version 5.4.0](https://github.com/Shopify/liquid/pull/1498). At the time of writing, Ruby Liquid version 5.4.0 is "unreleased", but inline comments [are already available in Shopify store templates](https://github.com/Shopify/liquid/pull/1498#issuecomment-1143594442).
Inline comments look like this:
```
{% # This is a comment %}
{%-
-%}
```
And inside `liquid` tags:
```
{% liquid
echo "Hello"
%}
```
You might also be interested in [this modified Prism language definition for Liquid](https://github.com/jg-rp/liquid/blob/docs/src/theme/prism-liquid-custom.js).

feat: inline comment tag

---

src/util/collection.ts
src/util/underscore.ts
test/integration/builtin/tags/for.ts
test/integration/builtin/tags/render.ts
test/integration/builtin/tags/tablerow.ts

This pull request adds support for looping over objects implementing JavaScript's [iteration protocols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols) in Liquid `for`, `render` and `tablerow` tags. It is also a potential solution to issue #515, without changing the behaviour of `Drop.valueOf()`.
Note that this means we can loop over [Maps](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) and [Sets](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set), as well as user-defined iterables.
**Example**
```js
const { Liquid } = require("liquidjs");
const engine = new Liquid();
class SomeIterable {
* [Symbol.iterator]() {
yield 'a'
yield 'b'
yield 'c'
}
}
engine
.parseAndRender(
"{% for …
```

feat: support iteration protocols

---

docs/source/filters/remove_last.md
docs/source/filters/replace_last.md
src/filters/string.ts
test/integration/filters/string.ts

This pull request adds the `remove_last` and `replace_last` filters to LiquidJS. These filters were added to [Shopify/liquid](https://github.com/Shopify/liquid/blob/master/History.md#520-2022-03-01) in version 5.2.0.

feat: remove_last and replace_last filters

---

docs/source/filters/date.md
docs/source/tutorials/options.md
docs/source/zh-cn/tutorials/options.md
src/filters/date.ts
src/liquid-options.ts
test/integration/filters/date.ts

doc: updates related to LiquidOptions.dateFormat
doc: revamped the date filter doc for easier reference
```
const liquidjs = require("liquidjs");
console.log(new liquidjs.Liquid({ dateFormat: '%d%q of %b %Y at %I:%M %P %z'})
.parseAndRenderSync(`{{ '1990-12-31T23:30:28Z' | date: undefined, -330 }}`));
=> 01st of Jan 1991 at 05:00 am +0530
```
Can be used as a workaround for #567, though the date format flags need to be strftime compatible.

new: LiquidOptions.dateFormat to override default date format

---

src/filters/array.ts

See https://jekyllrb.com/docs/liquid/filters

feat: Add support for the Jekyll push filter

---

src/filters/array.ts
test/integration/filters/array.spec.ts

See https://jekyllrb.com/docs/liquid/filters
I am sorting the array randomly and then picking the first N items or all items if there is no sample limit.

feat: Add support for the Jekyll sample filter

---

CONTRIBUTING.md
src/filters/array.ts
test/integration/filters/array.spec.ts

I thought `push` was broken because it doesn't work on the Playground but that's not the case. Here are the tests to prove it. Taken from the `concat` tests.
Related to #611

test: Add tests for `push`

---

bin/build-changelog.sh
bin/build-contributors.sh

These fixes make the sed invocations run on macOS but I am not sure if they will break the GNU sed invocations in return… I am hoping the GitHub Actions workflow will pass and config this is now portable between macOS and Ubuntu (what GitHub Actions is using).

fix: sed invocations to work out of the box on macOS

---

CONTRIBUTING.md

This should help anyone looking to test their changes they made to LiquidJS via the Playground site also provided in the repository.
I have also added basic information on where the Playground is and how to run it in general.
Closes #616.

docs: explain how to point the Playground at the local build

---

.github/workflows/check.yml

Once #615 is merged, the build script should work on macOS just as well as it does on Ubuntu and with this GitHub Actions matrix we can keep ensuring that it continues to work as it should.

chore: introduce a matrix with latest Ubuntu and macOS to test the build on macOS as well

---

src/util/strftime.spec.ts
src/util/strftime.ts

As written, the strftime module's `getSuffix` method (responsible for returning a date's ordinal string) works correctly for all dates in a month _except_ 11, 12, and 13. The existing code would return a string based on the last digit of the date. In American English, these three dates use the `th` suffix rather than `st`, `nd`, or `rd`.
This refactor/bug fix draws inspiration from [Rails' ActiveSupport ordinal inflector](https://github.com/rails/rails/blob/main/activesupport/lib/active_support/locale/en.rb). The linked Ruby code is designed to work with any number, so the bug fix to this library is simpler.
The test suite is also updated with additional examples to verify the correctness of these changes.

fix: strftime getSuffix works for all dates

---

src/filters/string.ts
test/integration/filters/string.spec.ts

When the substring to remove was anywhere but the end of the larger string, `remove_last` would eat an extra character.

fix: remove_last was eating an extra character

---

src/tags/case.ts
test/integration/tags/case.spec.ts

This is supported by Shopify liquid.

fix: case should allow multiple values separated by or

---

docs/source/tutorials/setup.md

Given in the published version, https://liquidjs.com/tutorials/options.md doesn't exist

docs: fix options link in setup tutorial

---

src/context/context.ts
src/util/underscore.ts
test/integration/tags/for.spec.ts

Please advise if this ain't the right way to fix this. I _think_ I didn't break anything and this may catch other cases of the same problem.
Fixes: [639](https://github.com/harttle/liquidjs/issues/639)

fix: for throws undefined var with a null value with strictVariables.

---

src/filters/html.ts
src/filters/string.ts
test/integration/filters/html.spec.ts
test/integration/filters/string.spec.ts

Not sure if they are handled by javascript already, but might as well consider the case.

fix: handle windows/dos newlines on `newline_to_br` and `strip_newlines`

---

src/filters/array.ts

Apply the same fix for `map` to `sort` and `where` which also rely on `_getFromScope`.

fix: sort and where bug when using `strictVariables`

---

docs/source/_data/sidebar.yml
docs/source/filters/sum.md
src/filters/array.ts
test/integration/filters/array.spec.ts

Implement `sum` filter from shopify liquid. Fixes #660 
Note the last two tests assert incompatibility with the ruby version, in particular coercing of `true`

feat: Array sum filter

---

package.json
rollup.config.mjs

Adjust the compatible typing file path to keep it consistent with historical versions.
Now
```ts
import { Tag } from 'liquidjs/dist/src/tags/assign'
```
Old
```ts
import { Tag } from 'liquidjs/dist/tags/assign'
```

chore: adjust typings dir

---

src/render/expression.spec.ts
src/render/operator.ts

This change allows the `contains` to be computed using the `toValue` of the items in the array.
Before this change if I had an array of "Drop" `contains` would not match against the value.
*this is not valid liquid, this is just to explain the case i'm trying to fix*
```
{{[Drop("hello"), Drop("bye")] | contains "hello"}} -> false
```
with the changes on this pr, it will return true.

fix: Rely on equal for computing contains

---

docs/themes/navy/layout/partial/all-contributors.swig
src/tags/case.ts
src/tags/if.ts
src/tags/unless.ts
test/e2e/issues.spec.ts
test/integration/tags/case.spec.ts
test/integration/tags/if.spec.ts
test/integration/tags/unless.spec.ts

This PR enforces a simple rule: don't render anything after an `else` branch.
There are several bugs currently where `if`, `unless` and `case` conditionals can have branches that occur after an `else` render, or that branches after an `else` can actually cause the `else` branch itself not to render.
Fixes: #670 and #672
```liquid
<p>If</p>
{% if false %}
don't show
{%- else -%}
show
{%- else -%}
don't show
{% endif %}
<p>If with Elsif</p>
{% if false %}
don't show
{%- else -%}
show
{%- elsif true -%}
don't show
{% endif %}
<p>Unless</p>
{% unless true %}
don't show
{%- else -%}
show
{%- else -%}
don't show
{% endunless %}
<p>Case</p>
{% case true %}
{%- when false- %}
don't show
{%- else -%}
show
{%- else -%}
don't show
{% endcase %}
<p>Case with When</p>
{% case true -%}
{% when false …
```

fix: in conditionals, don't render anything after an else branch

---

bin/build-contributors.sh
docs/source/filters/date.md
docs/source/tutorials/differences.md
docs/source/zh-cn/filters/date.md
docs/source/zh-cn/tutorials/differences.md
src/filters/date.ts
src/util/liquid-date.ts
src/util/strftime.ts
src/util/timezone-date.ts
test/integration/filters/date.spec.ts

- fix: added `%Z` flag for `date` filter
- docs: updated docs for date filter

fix: allow %Z for TimezoneDate, update docs accordingly #684

---

src/render/expression.ts
test/integration/liquid/strict.spec.ts

Closes https://github.com/harttle/liquidjs/issues/682

fix: Allow `lenientIf` for multiple operands (issue #682)

---

docs/source/tutorials/plugins.md

updated broken link to shopify/liquid differences page

docs: update broken link

---

src/drop/drop.ts
test/integration/drop/drop.spec.ts

The issue is that the type of `liquidMethodMissing` is too restrictive and only allows returning `string` rather than any supported value type. I ran into this issue when trying to return a `Drop` from `liquidMethodMissing` to enable dynamic lookups along an entire accessor chain.

fix: allow liquidMethodMissing to return any supported value type

---

src/render/boolean.spec.ts
src/render/boolean.ts
test/integration/tags/if.spec.ts

I noticed an inconsistency with drops where a drop's value will go through normal value resolution if used in an expression like `if drop > 10`, but it does not if the drop is the only part of the expression like `if drop` which causes it to always evaluate as truthy (because it's an object).
Shopify's Liquid implementation doesn't seem to support functionality similar to that of `valueOf` that we have in Liquid.js, so there's not prior art we can rely on there. Given if does seem to call `valueOf` when used with some type of operator I opted to make the bare drop case consistent with the existing behavior.

fix: use drop `valueOf` when evaluated as solitary condition

---

src/liquid-options.ts
src/parser/parser.ts
src/render/render.ts
src/util/error.ts
test/integration/util/error.spec.ts
test/stub/util.ts

Catching multiple errors before quit when `catchAllErrors` option is set. However there's some caveats.
1. It only catches all `LiquidError`, other errors like code bug are not catched in this way. So you'll need to check `err.name === 'LiquidErrors'` before using.
2. Top level tokennization errors are not catched, as there's no such concept of `Token` during this step. e.g. partial tag `{% foo`
3. Render errors should be catched perfectly. e.g. undefined variables, nonexist filters/tags, as well as errors thrown in filters/tags.

feat: support catching all errors, #220

---

package-lock.json
package.json
src/context/context.ts
src/render/render.ts

Resolves https://github.com/harttle/liquidjs/issues/728 by importing the `performance` object from its corresponding `perf_hooks` module.
Note that the `build-changelog.sh` script failed to run on my machine. I ended up forcing the commit with `--no-verify`. Perhaps the changelog should be added manually? Not sure if the `build-changelog.sh` script produces something that must be committed.

fix: Import performance object from perf_hooks

---

docs/source/tutorials/whitespace-control.md

I believe this is a typo, as the config has been called `trimOutputLeft`/`Right` for 5 years: https://github.com/harttle/liquidjs/blame/83922032b79fd678237de8786f0d75fb33e6312f/src/liquid-options.ts#L54
I'm new to this library, so I could also be missing out on something, in which case feel free to close, but the `trimValue` options do not exist on Config.

docs: Replace trimValue with trimOutput

---

docs/source/_data/sidebar.yml
docs/source/filters/find_index.md
docs/source/filters/find_index_exp.md
docs/source/filters/has.md
docs/source/filters/has_exp.md
docs/source/filters/reject.md
docs/source/filters/reject_exp.md
docs/source/filters/where.md
src/filters/array.ts
test/integration/filters/array.spec.ts

Implement new collection filters `find_index`, `reject` and `has` to match ruby side. Fixes #798

feat: add find_index, has, and reject filters

---

docs/source/tags/echo.md

DISCLAIMER: This may not be the proper way to approach the issue.
Although the Markdown code is proper, on the website itself it is incorrectly rendered as <code>{{\` and `}}</code> (see screenshot below).
The reason for the disclaimer above is that I’m imagining this may be an issue at the content rendering level, and my fix here is just a workaround of that issue. — Given this, I’ll not be offended if this PR of mine is rejected and closed. 🙂
<table><tr><td>
</table>

docs: Fix formatting bug in echo.md

---

README.md
src/drop/block-drop.ts
src/tags/block.ts
test/integration/tags/layout.spec.ts

`block.super` used to return a generator which emit contents into passed in `emmiter` and returns `undefined`, triggering `strictVariables` check. Credits to @kamikadzem22 for the investigation.
Furthermore, `block.super` seems to be a string but it isn't, in this PR also changes it to an actual string so it's more intuitive especially when users try to transform it.

fix: block.super with strictVariables, #806
